/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  compose: () => import("@/views/compose/index.vue"),
  contacts: () => import("@/views/contacts/index.vue"),
  "global-variables": () => import("@/views/global-variables/index.vue"),
  history: () => import("@/views/history/index.vue"),
  home: () => import("@/views/home/index.vue"),
  inbox: () => import("@/views/inbox/index.vue"),
  "oauth-callback": () => import("@/views/oauth-callback/index.vue"),
  settings: () => import("@/views/settings/index.vue"),
  smtp: () => import("@/views/smtp/index.vue"),
  "template-edit": () => import("@/views/template-edit/index.vue"),
  templates: () => import("@/views/templates/index.vue"),
};
