/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'api-keys',
    path: '/api-keys',
    component: 'layout.base$view.api-keys',
    meta: {
      title: 'api-keys',
      i18nKey: 'route.api-keys',
      hideInMenu: true,
      order: 10,
      icon: 'mdi:key-variant'
    }
  },
  {
    name: 'compose',
    path: '/compose',
    component: 'layout.base$view.compose',
    meta: {
      title: 'compose',
      i18nKey: 'route.compose',
      order: 2,
      icon: 'mdi:email-plus-outline',
      keepAlive: false
    }
  },
  {
    name: 'contacts',
    path: '/contacts',
    component: 'layout.base$view.contacts',
    meta: {
      title: 'contacts',
      i18nKey: 'route.contacts',
      order: 8,
      icon: 'mdi:book-account-outline'
    }
  },
  {
    name: 'global-variables',
    path: '/global-variables',
    component: 'layout.base$view.global-variables',
    meta: {
      title: 'global-variables',
      i18nKey: 'route.global-variables',
      order: 7,
      icon: 'mdi:variable'
    }
  },
  {
    name: 'history',
    path: '/history',
    component: 'layout.base$view.history',
    meta: {
      title: 'history',
      i18nKey: 'route.history',
      order: 5,
      icon: 'mdi:history'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      order: 1,
      icon: 'mdi:monitor-dashboard'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      hideInMenu: true
    }
  },
  {
    name: 'inbox',
    path: '/inbox',
    component: 'layout.base$view.inbox',
    meta: {
      title: 'inbox',
      i18nKey: 'route.inbox',
      order: 3,
      icon: 'mdi:email-open-outline'
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.base$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'oauth-callback',
    path: '/oauth-callback',
    component: 'layout.base$view.oauth-callback',
    meta: {
      title: 'oauth-callback',
      i18nKey: 'route.oauth-callback',
      hideInMenu: true
    }
  },
  {
    name: 'settings',
    path: '/settings',
    component: 'layout.base$view.settings',
    meta: {
      title: 'settings',
      i18nKey: 'route.settings',
      order: 6,
      icon: 'mdi:cog-outline'
    }
  },
  {
    name: 'smtp',
    path: '/smtp',
    component: 'layout.base$view.smtp',
    meta: {
      title: 'smtp',
      i18nKey: 'route.smtp',
      order: 3,
      icon: 'mdi:server'
    }
  },
  {
    name: 'template-edit',
    path: '/template-edit',
    component: 'layout.base$view.template-edit',
    meta: {
      title: 'template-edit',
      i18nKey: 'route.template-edit',
      hideInMenu: true,
      keepAlive: false
    }
  },
  {
    name: 'templates',
    path: '/templates',
    component: 'layout.base$view.templates',
    meta: {
      title: 'templates',
      i18nKey: 'route.templates',
      order: 4,
      icon: 'mdi:file-document-outline'
    }
  }
];
