/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'smtp',
    path: '/smtp',
    component: 'layout.base$view.smtp',
    meta: {
      title: 'smtp',
      i18nKey: 'route.smtp',
      icon: 'mdi:server',
      order: 2
    }
  },
  {
    name: 'templates',
    path: '/templates',
    component: 'layout.base$view.templates',
    meta: {
      title: 'templates',
      i18nKey: 'route.templates',
      icon: 'mdi:file-document-outline',
      order: 3
    }
  },
  {
    name: 'templates_editor',
    path: '/templates/editor',
    component: 'layout.base$view.templates_editor',
    meta: {
      title: 'templates_editor',
      i18nKey: 'route.templates_editor',
      hideInMenu: true
    }
  },
  {
    name: 'history',
    path: '/history',
    component: 'layout.base$view.history',
    meta: {
      title: 'history',
      i18nKey: 'route.history',
      icon: 'mdi:history',
      order: 4
    }
  },
  {
    name: 'settings',
    path: '/settings',
    component: 'layout.base$view.settings',
    meta: {
      title: 'settings',
      i18nKey: 'route.settings',
      icon: 'mdi:cog-outline',
      order: 5
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  }
];